[package]
name = "woah"
description = "🧰 nobody ever thought of a good scaffolding solution!?"
version = "1.0.0"
edition = "2021"

[dependencies]
bpaf = "0.9.12"
directories = "5.0.1"
once_cell = "1.19.0"
